# Generated by Django 5.0.6 on 2024-05-21 12:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('group_category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meal_type',
            field=models.CharField(choices=[('b', 'Breakfast'), ('d', 'Dinner'), ('l', 'Lunch')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cuisine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.cuisinetype'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.groupcategory'),
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='categories',
            field=models.ManyToManyField(related_name='group_categories', to='meals.maincategory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meals.maincategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
